In [5]:
import numpy as np

In [9]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [13]:
arr

array([1, 2, 3, 4, 5])

In [23]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [34]:
arrays_of_two = np.full((3,4),7)

In [36]:
print(arrays_of_two)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
