In [1]:
import numpy as np

In [8]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
arr[0]

array([1, 2, 3])

In [16]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
np.sum(arr, axis = 0)

array([12, 15, 18])

In [22]:
np.sum(arr, axis = 1)

array([ 6, 15, 24])

In [27]:
arr[0,2]

3

In [38]:
#arr[0:1,2:0]

array([], shape=(1, 0), dtype=int64)

In [41]:
arr[0:2, 1:3]

array([[2, 3],
       [5, 6]])

In [56]:
arr3D = np.array([
    [[1, 2, 3], 
     [4, 5, 6]],
    
[[7, 8, 9],
 [10, 11, 12]]

])

print(arr3D)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [58]:
print(arr3D[:,0,:])

[[1 2 3]
 [7 8 9]]


In [62]:
arr3D[:,0,:] = 0
#    [sheet , row , column]

In [54]:
# for change the element 

In [64]:
arr3D

array([[[ 0,  0,  0],
        [ 4,  5,  6]],

       [[ 0,  0,  0],
        [10, 11, 12]]])

In [68]:
arr3D[1,0,2] = 9
arr3D

array([[[ 0,  0,  0],
        [ 4,  5,  6]],

       [[ 0,  0,  9],
        [10, 11, 12]]])